first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
     path('', views.index, name='index'),
     path('form_name/', views.form_name_view, name='form_name_view'),
     path('users/', views.users, name='users')
]

first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('first_app/', include('first_app.urls')),
    path('user_auth/', include('user_auth.urls')),
]

user_auth/urls.py
from django.urls import path
from django.conf.urls import include
from user_auth import views

app_name = 'user_auth'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('special/', views.special, name='special'),
    ]

first_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class User(models.Model):
    name = models.CharField(max_length=264)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

user_auth/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pics = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import User

def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name needs to start with Z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email!=vmail:
            raise forms.ValidationError("Make sure emails match")

class NewUser(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

user_auth/forms.py
from django import forms
from django.contrib.auth.models import User
from user_auth.models import UserProfileInfo
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pics')

first_app/views.py
from django.shortcuts import render, redirect
from first_app.models import AccessRecord, Topic, Webpage, User
from . import forms

# Create your views here.
def index(request):
    Webpages_list = AccessRecord.objects.order_by('date')
    user = User.objects.all()
    date_dict = {'access_records': Webpages_list, 'user_list': user}
    return render(request,'first_app/index.html',context=date_dict)

def form_name_view(request):
    form = forms.FormName()
    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print('Validation Success')
            print('Name: '+form.cleaned_data['name'])
            print('Email: ' + form.cleaned_data['email'])
            print('Text: ' + form.cleaned_data['text'])
    return render(request, 'first_app/form_name.html', {'form': form})

def users(request):
    form = forms.NewUser()
    if request.method == 'POST':
        form = forms.NewUser(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('index')
        else:
            print('Error form invalid')
    return render(request, 'first_app/users.html', {'form': form})

user_auth/views.py
from django.shortcuts import render, redirect
from user_auth.forms import UserForm, UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'user_auth/index.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pics' in request.FILES:
                profile.profile_pics = request.FILES['profile_pics']
                profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
            return HttpResponse(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'user_auth/registration.html', {'user_form':user_form,
                                                               'profile_form':profile_form,
                                                               'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried tp login and failed')
            print('Username: {} and password: {}'.format(username, password))
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'user_auth/login.html', context={})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('You are logged in, Nice')

templates/first_app/form_name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<a href="{% url 'index' %}">Index</a>
<div class="container">
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>

</div>
</body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
</head>
<body>
<a href="{% url 'first_app:form_name_view' %}">Form name view</a>
<a href="{% url 'first_app:users' %}">Users Form</a>
    <h1>Welcome</h1>
    {% if access_records %}
        <table class="djangotwo">
            <thead>
                <th>File Name</th>
                <th>Date Accessed</th>
            </thead>
            {% for acc in access_records %}
                <tr>
                    <td>{{ acc.name }}</td>
                    <td>{{ acc.date }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>No access data found</p>
    {% endif %}
    <h1>User List</h1>

        {% if user_list %}

            {% for user in user_list %}
            <ul>
                <li> {{ user.name }}</li>
                <li> {{ user.email }}</li>
            </ul>
            {% endfor %}

        {% else %}
            <p>No user data found</p>
        {% endif %}



</body>
</html>

templates/first_app/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
</div>

</body>
</html>

templates/user_auth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Auth</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">Auth Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'user_auth:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'user_auth:special' %}">Special</a></li>
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'user_auth:user_logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'user_auth:user_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block body-block %}
    {% endblock %}
</div>
</body>
</html>

templates/user_auth/index.html
{% extends 'user_auth/base.html' %}
{% load static %}
{% block body-block %}
    <div class="jumbotron">
        <h1>Authentication</h1>
    </div>
{% endblock %}

templates/user_auth/login.html
{% extends 'user_auth/base.html' %}
{% load static %}
{% block body-block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
        <form action="{% url 'user_auth:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username: </label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password </label>
            <input type="password" name="password" placeholder="Enter Password">
            <input type="submit" value="Login">
        </form>
    </div>
{% endblock %}

templates/user_auth/registration.html
{% extends 'user_auth/base.html' %}
{% load static %}
{% block body-block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering</h1>
        {% else %}
            <h1>Register here</h1>
            <h3>Fill out the form:</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}